
enum ActionTypes {
    GO_TO_NEXT_PAGE = 'GO_TO_NEXT_PAGE',
    SET_TOTAL_PAGES = 'SET_TOTAL_PAGES',
    FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE',
    INCREASE_TOTAL_LIKES = 'INCREASE_TOTAL_LIKES',
    DECREASE_TOTAL_LIKES = 'DECREASE_TOTAL_LIKES',
}

export default ActionTypes;